var LANG_JSON_DATA = {
		
		"KR" : {
				"modal_confirm_btn" : "확인",
				"modal_title" : "알림",
				"side_menu_dashboard" : "Dashboard",
				"side_menu_flight_plan" : "비행계획",
				"side_menu_flight_plan_design" : "계획 설계",
				"side_menu_flight_plan_list" : "계획 목록",
				"side_menu_flight_plan_mon" : "계획 모니터링",
				"side_menu_flight_record" : "비행 기록",
				"side_menu_flight_record_upload" : "기록 업로드",
				"side_menu_flight_record_list" : "기록 보기",
				"side_menu_qa" : "문의하기",
				"side_menu_links" : "관련사이트",
				"side_menu_links_comm" : "DUNI 커뮤니티",
				"side_menu_links_blog" : "DUNI 블로그",
				"side_menu_links_apis" : "DUNI Open APIs",
				"side_menu_links_dev" : "DUNI 개발자 사이트",
				"modifyBtnForMovieData" : "영상정보 수정",
				"title_for_moviedata_label" : "영상 제목",
				"desc_for_moviedata_label" : "영상 설명",
				"privacy_for_moviedata_label" : "공개 수준",
				"option_public_label" : "공개",
				"option_unlisted_label" : "일부공개(링크가 있는 사용자만 영상을 볼수 있음)",
				"option_private_label" : "비공개",
				"movieButton" : "유튜브에 영상 업로드",
				"youtube_url_label" : "유튜브 영상 주소",
				"top_menu_logout" : "로그아웃",
				"top_menu_token" : "개발자 토큰",
				"data_count_msg" : "님의 데이터 현황",
				"map_kind_label" : "지도 종류",
				"go_index_direct_label" : "바로가기",
				"phone_label" : "전화번호",
				"email_label" : "이메일",
				"name_label" : "이름",
				"status_label" : "상태",
				"date_label" : "등록일",
				"register_label" : "가입하기",
				"manage_label" : "관리",
				"input_memo_label" : "메모입력",
				"qa_label" : "질문/답변 공간입니다",
				"altitude_label" : "비행고도",
				"privacy_link_label" : "개인정보취급방침 보기",
				"privacy_link" : "https://pilot.duni.io/privacy.html",
				"btnForRegistMission" : "계획등록",
				"btnForClearMission" : "초기화",
				"btnForGetMissionList" : "비행계획 목록 불러오기",
				"btnForLoadFlightList" : "비행기록 목록 불러오기",
				"btnStartMon" : "모니터링 시작하기",
				"center_about_title" : "이곳에 관하여...",
				"center_example_title" : "사용예시",				
				"msg_no_mission" : "비행계획이 존재하지 않습니다.",
				"msg_error_sorry" : "오류가 발생했습니다. 죄송합니다. 잠시후 다시 시도해 주세요.",
				"msg_no_flight_record" : "존재하는 비행기록이 없습니다.",
				"msg_no_data" : "존재하는 데이터가 없습니다.",
				"msg_load_more" : "더 불러오기",
				"msg_failed_to_get_position" : "대상 위치 파악 실패",
				"msg_modify" : "수정",
				"msg_remove" : "삭제",
				"msg_apply" : "적용",
				"msg_agree" : "동의합니다",
				"msg_register" : "가입하기",
				"msg_back" : "돌아가기",
				"msg_upload" : "업로드",
				"msg_you_are_not_member" : "등록되어 있지 않은 계정 입니다.",
				"msg_are_you_sure" : "정말로 진행하시겠습니까?",
				"msg_modify_memo" : "메모 수정",
				"msg_fill_memo" : "메모 내용을 입력해 주세요",
				"msg_success" : "반영되었습니다!",				
				"msg_tracker" : "현재 위치를 지도에 표시하기",
				"msg_register_success" : "축하드립니다. 성공적으로 가입되었습니다.",
				"msg_email_is_already_exist" : "이미 사용중인 이메일 주소입니다. 다른 이메일 주소를 입력해 주세요.",
				"msg_input_name" : "이름을 입력해 주세요.",
				"msg_input_email" : "이메일을 입력해 주세요.",
				"msg_input_phone" : "전화번호를 입력해 주세요.",
				"msg_input_mission_name" : "비행계획의 이름을 입력해 주세요.",
				"msg_input_record_name" : "비행기록의 이름을 입력해 주세요.",
				"msg_wrong_input" : "잘못 입력하셨습니다.",
				"msg_input_speed" : "비행계획 수행시 속도를 입력해 주세요. (m/s)",
				"msg_error_index_pre" : "오류 : 인덱스 - ",
				"msg_error_index_post" : " / 비어있는 파라메터가 존재합니다.",
				"msg_error_check" : "오류를 확인해 주세요.",
				"msg_select_file" : "파일을 선택해 주세요",
				"msg_modify_youtube_data" : "영상정보 수정",
				"msg_close_youtube_data" : "영상정보 닫기",
				"msg_dji_file_upload" : "DJI 비행기록 파일 업로드",
				"msg_duni_file_upload" : "DUNI 비행기록 업로드",
				"r_count_label" : "비행기록 수",
				"f_count_label" : "비행계획 수",
				"dji_flight_record_get_label" : "비행기록 파일 얻는 방법 (클릭)",
				"duni_flight_record_format_label" : "비행기록 파일 포맷 (클릭)",
				"page_center_title" : "DUNI PILOT Center",
				"page_qa_title" : "묻고 답하기",
				"page_list_title" : "비행계획 목록",
				"page_flight_rec_view_title" : "비행기록 보기",
				"page_flight_rec_upload_title" : "비행기록 업로드",
				"page_monitor_title" : "비행계획 모니터",
				"page_mission_design_title" : "비행계획 설계",
				"page_dromi_title" : "Dromi",
				"page_dromi_list_title" : "Dromi Data View",
				"fill_info_label" : "내용을 채우신 후 '가입하기'버튼을 클릭해 주세요.",
				"register_explain_label" : "하기의 '개인정보취급방침'의 내용에 동의하시면 아래 '동의합니다' 버튼을 클릭해 주세요.",
				"center_about_content" : "<p>드론의 비행계획을 쉽게 디자인하고 비행기록과 상황를 확인할 수 있는 곳입니다.</p>" +
																	"<p>디자인 한 비행계획은 DUNI앱과 DJI제품의 드론에서 사용 할 수 있습니다. DUNI앱은 현재 개발중이며 곧 안드로이드/iOS버전이 배포될 예정입니다. ('비행계획' > '계획 설계' 메뉴)</p>" +
																	"<p>DUNI앱의 안드로이드 버전은 소스코드가 공개되어 있습니다. <a href='http://code.duni.io/' target=_new>이곳</a>에서 확인할 수 있습니다.</p>" +
																	"<p>DJI 비행기록 파일과 드론 영상이 있는 유튜브 URL을 업로드하면 자세한 비행기록을 확인할 수 있습니다. ('비행기록' > '기록 업로드' 메뉴)</p>" +
																	"<p>상단의 <i class='fa fa-user fa-fw'></i> 아이콘을 클릭하면 본인의 개발자 Token을 확인할 수 있습니다.</p>",
				"collapseRecordFileParams" : "<br><hr size=1><p><b>안드로이드</b></p>"
							+ "<p>- 내 파일 > 내장 메모리 > DJI > dji.go.v4 > FlightRecord > FlightRecord_연월일시.txt</p>"
							+ "<br><p><b>iOS (하기 링크의 내용을 참고하여 파일을 추출해 주세요)</b></p>"
							+ "<p>- <a href='https://m.blog.naver.com/PostView.nhn?blogId=apache81&logNo=220423814490' target=new>https://m.blog.naver.com/PostView.nhn?blogId=apache81&logNo=220423814490</a></p>"
							+ "<p>- <a href='http://blog.daum.net/dipod/857' target=new>http://blog.daum.net/dipod/857</a></p>"
							+ "<p>- <a href='https://www.youtube.com/watch?v=59pE9N3pXdg' target=new>https://www.youtube.com/watch?v=59pE9N3pXdg</a></p>",
		},
				
		
		"EN" : {
				"modal_confirm_btn" : "Confirm",
				"modal_title" : "Notification",
				"side_menu_dashboard" : "Dashboard",
				"side_menu_flight_plan" : "Flight mission",
				"side_menu_flight_plan_design" : "Mission design",
				"side_menu_flight_plan_list" : "Mission list",
				"side_menu_flight_plan_mon" : "Mission Monitoring",
				"side_menu_flight_record" : "Flight record",
				"side_menu_flight_record_upload" : "Upload record",
				"side_menu_flight_record_list" : "Record list",
				"side_menu_qa" : "QnA",
				"side_menu_links" : "Links",
				"side_menu_links_comm" : "DUNI Community",
				"side_menu_links_blog" : "DUNI Blog",
				"side_menu_links_apis" : "DUNI Open APIs",
				"side_menu_links_dev" : "DUNI Developer",
				"modifyBtnForMovieData" : "Modify Video info.",
				"title_for_moviedata_label" : "Video title",
				"desc_for_moviedata_label" : "Video description",
				"privacy_for_moviedata_label" : "privacy level",
				"option_public_label" : "public",
				"option_unlisted_label" : "unlisted",
				"option_private_label" : "private",
				"movieButton" : "Upload video to Youtube",
				"youtube_url_label" : "Youtube video URL",
				"top_menu_logout" : "Logout",
				"top_menu_token" : "Token",
				"data_count_msg" : "'s data status",
				"map_kind_label" : "Map kinds",
				"go_index_direct_label" : "Go",
				"phone_label" : "Phonenumber",
				"email_label" : "Email",
				"name_label" : "Name",
				"status_label" : "Status",
				"date_label" : "Date",
				"register_label" : "Registration",
				"manage_label" : "Manage",
				"input_memo_label" : "Memo",
				"qa_label" : "QA page",
				"altitude_label" : "Altitude",
				"privacy_link_label" : "Privacy policy",
				"privacy_link" : "https://pilot.duni.io/privacy.html",
				"btnForRegistMission" : "Mission Register",
				"btnForClearMission" : "Clear",
				"btnForGetMissionList" : "Load mission list",
				"btnForLoadFlightList" : "Load record list",
				"btnStartMon" : "Start monitoring",
				"center_about_title" : "About ...",
				"center_example_title" : "Example",				
				"msg_no_mission" : "There is no mission or something wrong.",
				"msg_error_sorry" : "Error. Sorry, please try again later.",
				"msg_no_data" : "There is no data",
				"msg_modify" : "Modify",
				"msg_remove" : "Delete",
				"msg_apply" : "Apply",
				"msg_agree" : "I Agree",
				"msg_register" : "Register",
				"msg_back" : "Back",
				"msg_upload" : "Upload",
				"msg_no_flight_record" : "There is no flight record or something wrong.",
				"msg_failed_to_get_position" : "Failed to get object position",
				"msg_load_more" : "More ...",
				"msg_you_are_not_member" : "You are not registered here.",
				"msg_are_you_sure" : "Are you sure ?",
				"msg_modify_memo" : "Update Memo",
				"msg_fill_memo" : "Memo is empty. Please, write something.",
				"msg_success" : "Success",
				"msg_tracker" : "Move map to the current location",
				"msg_register_success" : "Congratulation!! Successfully, registered !",
				"msg_email_is_already_exist" : "Email is already in use. Please, enter another email",
				"msg_input_name" : "Please, enter your name.",
				"msg_input_email" : "Please, enter your email.",
				"msg_input_phone" : "Please, enter your phone-number.",
				"msg_input_mission_name" : "Please, Input Mission name.",
				"msg_input_record_name" : "Please, Input flight record name.",
				"msg_wrong_input" : "Please input valid data.",
				"msg_input_speed" : "Please enter the speed when performing the flight mission.  (m/s)",
				"msg_error_index_pre" : "Error : Index - ",
				"msg_error_index_post" : " / There is empty parameter.",
				"msg_error_check" : "Please, check errors.",
				"msg_select_file" : "Please, select any file.",
				"msg_modify_youtube_data" : "Modify youtube info",
				"msg_close_youtube_data" : "Close youtube info",
				"msg_dji_file_upload" : "upload DJI Flight-record file",
				"msg_duni_file_upload" : "upload DUNI Flight-record file",
				"r_count_label" : "record #",
				"f_count_label" : "mission #",
				"dji_flight_record_get_label" : "How to get DJI flight-record file (Click)",
				"duni_flight_record_format_label" : "DUNI Flight record format (Click)",
				"page_center_title" : "DUNI PILOT Center",
				"page_qa_title" : "QnA",
				"page_list_title" : "Flight Mission List",
				"page_flight_rec_view_title" : "Flight Record View",
				"page_flight_rec_upload_title" : "Flight Record Upload",
				"page_monitor_title" : "Flight Mission Monitor",
				"page_mission_design_title" : "Flight Mission Design",
				"page_dromi_title" : "Dromi",
				"page_dromi_list_title" : "Dromi Data View",
				"fill_info_label" : "Please fill the form in and click the 'Register' button.",
				"register_explain_label" : "If you agree with the 'Privacy Policy' below, please click the 'I agree' button below.",
				"center_about_content" : "<p>This is where you can easily design the drone's flight mission and check flight records and the situation.</p>" +
																"<p>The flight mission you designed can be used in DUNI app and in the drone of DJI product. DUNI app is currently under development and Android/iOS version will be distributed soon. ('Flight mission' > 'mission design' menu)</p>" +
																"<p>The Android version of the DUNI app has a source code and it is opened. <a href='http://code.duni.io/' target=_new>Here</a></p>" +
																"<p>Upload the Drone's video to Youtubu or YouTube URL with the video to see detailed flight records. ('Flight record' > 'Upload record' Menu)</p>" +
																"<p>Click <i class='fa fa-user fa-fw'></i> icon at the top to see your developer Token.</p>",
				"collapseRecordFileParams" : "<br><hr size=1><p><b>Android</b></p>"
							+ "<p>- My file > Internal storage > DJI > dji.go.v4 > FlightRecord > FlightRecord_yyyymmddhh.txt</p>"
							+ "<br><p><b>iOS (Please, refer to links below)</b></p>"
							+ "<p>- <a href='https://m.blog.naver.com/PostView.nhn?blogId=apache81&logNo=220423814490' target=new>https://m.blog.naver.com/PostView.nhn?blogId=apache81&logNo=220423814490</a></p>"
							+ "<p>- <a href='http://blog.daum.net/dipod/857' target=new>http://blog.daum.net/dipod/857</a></p>"
							+ "<p>- <a href='https://www.youtube.com/watch?v=59pE9N3pXdg' target=new>https://www.youtube.com/watch?v=59pE9N3pXdg</a></p>",
		}
			
};
