/*
Copyright 2020 APLY Inc. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

var LANG_JSON_DATA = {
	"KR": {
    	"modal_yes_btn": "네",
        "modal_confirm_btn": "확인",
        "modal_title": "알림",
        "side_menu_dashboard": "Dashboard",
        "side_menu_flight_plan": "비행계획",
        "side_menu_flight_plan_design": "비행계획 설계",
        "side_menu_flight_plan_list": "비행계획 목록",
        "side_menu_flight_plan_mon": "드론위치 보기",
        "side_menu_flight_record": "비행영상 기록",
        "side_menu_flight_record_upload": "비행영상 기록 업로드/판매",
        "side_menu_flight_record_list": "내 기록 보기",
        "side_menu_flight_record_public_list": "공개 기록 보기",
        "side_menu_qa": "문의하기",
        "side_menu_lab": "Lab",
        "side_menu_dev": "Developer",
        "side_menu_links": "관련사이트",
        "side_menu_links_duni": "드론 서비스 매칭 플랫폼",
        "side_menu_links_comm": "DUNI 커뮤니티",
        "side_menu_links_blog": "DUNI 블로그",
        "side_menu_links_apis": "DUNI Open APIs",
        "side_menu_links_dev": "DUNI 개발자 사이트",
        "side_menu_links_codes": "DUNI 코드",
        "side_menu_links_samples": "DUNI 코드 예제",
        "title_for_company_flightlist": "비행영상 및 드론기업",
        "title_company_chkbox": "드론기업(드론전문교육기관포함)",
        "title_history_chkbox": "비행영상",        
        "modifyBtnForMovieData": "영상정보 수정",
        "flighttime_input_data_label": "촬영시각",
        "registered_datetime_label" : "등록시각",
        "option_public_label": "공개",
        "option_unlisted_label": "일부공개(링크가 있는 사용자만 영상을 볼수 있음)",
        "option_private_label": "비공개",
        "uploadVideoToYoutubeButton": "유튜브에 영상 등록",
        "youtube_url_label": "유튜브 URL",
        "menu_left_top_title_label": "파일럿 센터",
        "top_menu_logout": "로그아웃",
        "top_menu_token": "개발자 토큰",
        "data_count_msg": "님의 프로필",
        "all_member_msg": "전체 멤버",
        "shared_record_data_msg": "공유받은 데이터입니다.",
        "map_kind_label": "지도 종류",
        "go_index_direct_label": "바로가기",
        "mode_developer_label": "Lab으로 바꾸기",
        "mode_pilot_label": "파일럿뷰로 바꾸기",
        "phone_label": "전화번호",
        "email_label": "이메일",
        "name_label": "이름",
        "status_label": "상태",
        "date_label": "등록일",
        "badge_nickname_label": "배지 표시용 콜싸인(또는 이름)",
        "register_label": "가입하기",
        "manage_label": "관리",
        "input_memo_label": "메모",
        "input_tag_label": "태그",
        "qa_label": "최근 게시물",
        "stop_share_label": "공유해제",
        "badge_code_label": "배지 코드",
        "privacy_link_label": "개인정보취급방침 보기",
        "btnForBadge_make": "배지 생성하기",
        "btnForBadge_del": "배지 삭제하기",
        "btnForSharing": "공유하기",
        "btnForOpening": "공개하기",
        "btnForLink": "링크 생성하기",
        "btnForRegistMission": "계획등록",
        "btnForClearMission": "초기화",
        "btnForGetMissionList": "비행계획 목록 불러오기",
        "btnForLoadFlightList": "기록 목록 불러오기",
        "btnStartMon": "모니터링 시작",
        "btnStopMon": "모니터링 중지",
        "btnForFilter": "필터적용",
        "btnForFilter_rel": "필터해제",
        "btnForAddressCheck": "주소확인",
        "center_about_title": "DUNI 파일럿 센터를 소개합니다.",
        "center_example_title": "사용예시",
        // 전화번호 인증
        "msg_phone_already_exists" : "이미 사용중인 전화번호입니다. 다른 번호를 입력해주세요.",
        "msg_verification_code_sent" : "인증번호가 전송되었습니다.",
        "msg_wrong_phone_format" : "잘못된 전화번호이거나 전화번호 형식이 올바르지 않습니다. 다시 입력해주세요.",
        "msg_wrong_verification_code" : "인증번호가 일치하지 않습니다. 다시 입력해주세요.",
        "msg_phone_verified" : "인증되었습니다",
        "msg_phone_verification_timeout" : "인증번호 입력시간이 만료되었습니다. 다시 시도해주세요.",
        "msg_code_empty" : "인증번호를 입력해주세요.",
        "msg_phone_not_verified" : "전화번호인증은 필수입니다. 인증해주세요.",
        // 전화번호인증 end
        "msg_is_sync_data" : "영상의 길이와 비행기록의 길이가 일치하나요?",
        "msg_youtube_uploaded" : "수정을 반영하려면 \"적용\" 버튼을 클릭해 주세요.",
        "msg_do_login" : "로그인이 필요한 서비스 입니다.",
        "msg_login_another_device_sorry" : "다른 기기에서 로그인을 하였거나 일시적인 문제가 발생하였습니다.",
        "msg_notice": "* 전체 비행시간은 2020년 9월 9일 이후부터 업로드 한 비행기록에서 집계 하는 수치입니다.",
        "msg_no_mission": "비행계획이 존재하지 않습니다.",
        "msg_stop_share_before_remove": "공유되어 있는 기록입니다. 공유를 먼저 해제해 주세요.",
        "msg_error_sorry": "오류가 발생했습니다. 죄송합니다. 잠시후 다시 시도해 주세요.",
        "msg_error": "오류가 발생했습니다.",
        "msg_show_token":"토큰 보기",
        "msg_hide_token":"토큰 감추기",
        "msg_error_same_record_exist": "동일한 비행기록이 존재합니다. 기존 비행기록을 삭제하고 다시 업로드 하거나 다른 비행기록을 업로드해 주세요.",
        "msg_failed_to_load_map_sorry": "지도를 불러오는 중에 오류가 발생했습니다. 잠시후 다시 시도해 주세요.",
        "msg_sorry_now_on_preparing": "죄송합니다. 현재 이 기능은 준비 중입니다.",
        "msg_sorry_now_on_preparing_youtube": "죄송합니다. 현재 이 기능은 준비 중입니다. 영상을 유튜브 사이트에서 업로드 한 후, 생성되는 영상의 링크를 '유튜브 영상주소'에 설정하실 수 있습니다.",
        "msg_no_flight_record": "비행영상 기록이 존재하지 않습니다.",
        "msg_no_data": "존재하는 데이터가 없습니다.",
        "msg_no_email": "존재하지 않는 이메일 입니다.",
        "msg_load_more": "더 불러오기",
        "msg_failed_to_get_position": "대상 위치 파악 실패",
        "msg_modify": "수정",
        "msg_remove": "삭제하기",
        "msg_apply": "적용",
        "msg_cancel": "취소",
        "msg_agree": "동의합니다",
        "msg_register": "가입하기",
        "msg_back": "돌아가기",
        "msg_upload": "업로드",
        "msg_you_are_not_member": "등록되어 있지 않은 계정 입니다.",
        "msg_are_you_sure": "정말로 진행하시겠습니까?",
        "msg_modify_memo": "메모 수정",
        "msg_modify_tag": "태그 수정",
        "msg_fill_memo": "메모 내용을 입력해 주세요",
        "msg_fill_tag": "태그를 입력해 주세요",
        "msg_success": "반영되었습니다!",
        "msg_tracker": "현재 위치를 지도에 표시하기",
        "msg_register_success": "축하드립니다. 성공적으로 가입되었습니다.",
        "msg_email_is_already_exist": "이미 사용중인 이메일 주소입니다. 다른 이메일 주소를 입력해 주세요.",
        "msg_name_is_already_exist": "이미 사용중인 이름 입니다. 다른 이름을 입력해 주세요.",
        "msg_input_name": "이름을 입력해 주세요.",
        "msg_input_email": "이메일을 입력해 주세요.",
        "msg_input_member_email": "DUNI 파일럿 센터 멤버의 이메일 주소를 입력해 주세요.",
        "msg_sure_for_public": "정말로 공개 하시겠습니까?",
        "msg_input_phone": "전화번호를 입력해 주세요.",
        "msg_input_mission_name": "비행계획의 이름을 입력해 주세요.",
        "msg_input_record_name": "기록의 이름을 입력해 주세요.",
        "msg_wrong_input": "잘못 입력하셨습니다.",
        "msg_wrong_youtube_url_input": "잘못된 유튜브 주소입니다.",
        "msg_input_speed": "비행계획 수행시 속도를 입력해 주세요. (m/s)",
        "msg_error_index_pre": "오류 : 인덱스 - ",
        "msg_error_index_post": " / 비어있는 파라메터가 존재합니다.",
        "msg_error_check": "오류를 확인해 주세요.",
        "msg_select_file": "비행기록 파일을 선택해 주세요",
        "msg_select_another_file": "죄송합니다. 비행기록 파일을 분석할 수가 없습니다. 다른 파일을 선택해 주세요.",
        "msg_select_video_file" : "영상 파일을 선택해 주세요.",
        "msg_select_any_file": "비행기록 파일을 선택하거나 유튜브 영상정보를 입력해 주세요",
        "msg_modify_youtube_data": "영상정보 수정",
        "msg_close_youtube_data": "영상정보 닫기",
        "msg_dji_file_upload": "DJI 비행기록 파일",
        "msg_duni_file_upload": "DUNI 비행기록 파일",
        "msg_record_search_key": "비행기록 검색",
        "msg_mission_search_key": "비행계획 검색",
        "msg_address_checked": "확인을 완료했습니다.",
        "msg_video_upload_success": "영상을 성공적으로 업로드 하였습니다",
        "msg_input_corrent_address" : "올바른 주소를 입력한 후 '주소확인'을 클릭하세요.", 
        "badgeHelpContent": "'html'코드의 삽입이 가능한 홈페이지나 블로그, 웹사이트 게시물에 아래의 코드를 복사해서 붙여 넣으세요. 비행기록을 자연스럽게, 멋지게 증명하실 수 있습니다.",
        "tab_menu_upload_selector_address" : "촬영지 주소 입력",
        "open_record_label": "공개 비행영상 기록",
        "label_set_youtube_url": "Youtube URL 입력",
        "label_set_no_video" : "영상 없음",
        "label_upload_movie": "영상 업로드",
        "tab_menu_upload_selector_dji": "비행기록 업로드",
        "tab_menu_upload_selector_address": "촬영지 주소 입력",
        "more_label": "더보기 ...",
        "latitude_label": "위도",
        "longitude_label": "경도",
        "altitude_label": "고도",
        "roll_label": "롤(roll)",
        "pitch_label": "피치(pitch)",
        "yaw_label": "헤드(head)",
        "speed_label": "속도(m/s)",
        "action_label": "액션",
        "help_label": "도움말",
        "Aerial_label": "항공뷰",
        "Aerial_label_label": "항공뷰 + 레이블",
        "Road_label": "도로뷰",
        "average_alltime_label": "전체 회원의 평균 비행시간(분)",
        "average_rcount_label": "전체 회원의 평균 비행횟수",
        "r_count_label": "비행회수",
        "f_count_label": "비행계획수",
        "a_time_label": "총 비행시간",
        "a_time_min_label": "분",
        "callsign_pre_label": "DUNI 파일럿",
        "dji_flight_record_get_label": "얻는 방법 : 클릭",
        "duni_flight_record_format_label": "DUNI 비행기록 파일 포맷 (클릭)",
        "page_center_title": "DUNI 파일럿 센터",
        "page_list_title": "비행계획 보기",
        "page_flight_rec_view_title": "나의 비행기록 보기",
        "page_flight_rec_public_view_title": "공개 비행기록 보기",
        "page_flight_rec_upload_title": "비행기록 업로드",
        "page_monitor_title": "드론위치 보기",
        "page_mission_design_title": "비행계획 설계",
        "page_dromi_title": "Dromi",
        "page_dromi_list_title": "Dromi Data View",
        "fill_info_label": "내용을 채우신 후 '가입하기'버튼을 클릭해 주세요.",
        "mission_about_content": "내가 설계한 비행계획을 검색해보세요.",
        "record_list_about_content": "내 비행기록을 선택해서 영상과 맵으로 확인해 보세요.",
        "record_public_list_about_content": "다른 회원들의 비행기록을 확인해 보세요.",
        "register_explain_label": "하기의 '개인정보취급방침'의 내용에 동의하시면 아래 '동의합니다' 버튼을 클릭해 주세요.",
        "monitor_about_content": "DUNI 앱을 활용하여 현재 드론의 위치를 실시간으로 모니터링할 수 있습니다.",
        "upload_about_content": "내 비행기록을 업로드하세요.",
        "design_about_content": "설계한 비행계획은 DUNI 앱과 DJI 제품의 드론에서 사용할 수 있습니다.",
        "head_pilot_title": "파일럿 센터 for Pilot",
        "head_developer_title": "파일럿 센터 for Lab",
        "center_about_pilot_title": "파일럿 뷰를 소개합니다.",
        "center_about_developer_title": "Lab을 소개합니다.",
        "center_about_pilot_content": "드론의 비행기록을 업로드하여 영상과 함께 확인할 수 있습니다.",
        "center_about_developer_content": "DUNI Lab에서 드론의 비행계획을 쉽게 디자인 해 보세요.",
        "dev_token_title": "개발자 토큰 발급",
        "collapseRecordFileParams": "<br><hr size=1><p><b>안드로이드</b></p>"
            + "<p>- 내 파일 > 내장 메모리 > DJI > dji.go.v4 > FlightRecord > FlightRecord_연월일시.txt</p>"
            + "<p>또는, - 내 파일 > 내장 메모리 > DJI > com.dji.industry.pilot > FlightRecord > FlightRecord_연월일시.txt</p>"
            + "<p>또는, - 내 파일 > 내장 메모리 > DJI > [그외 앱이름] > FlightRecord > FlightRecord_연월일시.txt</p>"
            + "<br><p><b>iOS (하기 링크의 내용을 참고하여 파일을 추출해 주세요)</b></p>"
            + "<p>- <a href='https://m.blog.naver.com/PostView.nhn?blogId=apache81&logNo=220423814490' target=new>https://m.blog.naver.com/PostView.nhn?blogId=apache81&logNo=220423814490</a></p>"
            + "<p>- <a href='http://blog.daum.net/dipod/857' target=new>http://blog.daum.net/dipod/857</a></p>"
            + "<p>- <a href='https://www.youtube.com/watch?v=59pE9N3pXdg' target=new>https://www.youtube.com/watch?v=59pE9N3pXdg</a></p>",
        "youtubeTOS" : "동영상을 제출하면 YouTube <a href='https://www.youtube.com/t/terms' target=_new>서비스 약관</a> 및 <a href='https://www.youtube.com/yt/about/policies/' target=_new>커뮤니티 가이드</a>에 동의하게 됩니다.",
    },


    "EN": {
    	"modal_yes_btn": "Yes",
        "modal_confirm_btn": "Confirm",
        "modal_title": "Notification",
        "side_menu_dashboard": "Dashboard",
        "side_menu_flight_plan": "Flight Mission",
        "side_menu_flight_plan_design": "Flight Mission Design",
        "side_menu_flight_plan_list": "Flight Mission List",
        "side_menu_flight_plan_mon": "Drone Location",
        "side_menu_flight_record": "Flight Record",
        "side_menu_flight_record_upload": "Upload Record",
        "side_menu_flight_record_list": "Record List",
        "side_menu_flight_record_public_list": "Public Record list",
        "side_menu_qa": "QnA",
        "side_menu_lab": "Lab",
        "side_menu_dev": "Developer",
        "side_menu_links": "Links",
        "side_menu_links_duni": "Drone Service Matching Platform",
        "side_menu_links_comm": "DUNI Community",
        "side_menu_links_blog": "DUNI Blog",
        "side_menu_links_apis": "DUNI Open APIs",
        "side_menu_links_dev": "DUNI Developer",
        "side_menu_links_codes": "DUNI Codes",
        "side_menu_links_samples": "DUNI Code Samples",
        "title_for_company_flightlist": "Public flight records in DUNI PILOT CENTER and Drone companies",
        "title_company_chkbox": "Drone Company(Including Drone Education Institution)",
        "title_history_chkbox": "Flight Record",        
        "modifyBtnForMovieData": "Modify Video info.",
        "flighttime_input_data_label": "Recorded Date/Time",
        "registered_datetime_label": "Registered Date/Time",
        "option_public_label": "public",
        "option_unlisted_label": "unlisted",
        "option_private_label": "private",
        "uploadVideoToYoutubeButton": "Upload video to Youtube",
        "youtube_url_label": "Youtube URL",
        "menu_left_top_title_label": "PILOT Center",
        "top_menu_logout": "Logout",
        "top_menu_token": "Token",
        "all_member_msg": "All members",
        "shared_record_data_msg": " is shared record.",
        "data_count_msg": "s aviation profile",
        "map_kind_label": "Map kinds",
        "go_index_direct_label": "Go",
        "mode_developer_label": "Go to Lab & Developer",
        "mode_pilot_label": "Go to Pilot View",
        "phone_label": "Phonenumber",
        "email_label": "Email",
        "name_label": "Name",
        "status_label": "Status",
        "date_label": "Date",
        "badge_nickname_label": "Call sign(or name) for badge",
        "register_label": "Registration",
        "manage_label": "Manage",
        "input_memo_label": "Memo",
        "input_tag_label": "Tag",
        "qa_label": "Latest post",
        "stop_share_label": "Stop sharing",
        "badge_code_label": "Badge code",
        "btnForSharing": "Share",
		"btnForOpening": "Open",
        "btnForLink": "Creating a new link",
        "privacy_link_label": "Privacy policy(KR)",
        "btnForBadge_make": "Generate badge code",
        "btnForBadge_del": "Delete badge",
        "btnForRegistMission": "Mission Register",
        "btnForClearMission": "Clear",
        "btnForGetMissionList": "Load mission list",
        "btnForLoadFlightList": "Load record list",
        "btnStartMon": "Start monitoring",
        "btnStopMon": "Stop monitoring",
        "btnForFilter": "Filter on",
        "btnForFilter_rel": "Filter off",
        "btnForAddressCheck": "Check address",
        "center_about_title": "About ...",
        "center_example_title": "Example",
        // 전화번호 인증
        "msg_phone_already_exists" : "Phone number already registered. Please try a different number",
        "msg_verification_code_sent" : "Verification code sent.",
        "msg_wrong_phone_format" : "Phone number does not exist. Please check your number.",
        "msg_wrong_verification_code" : "Incorrect verification code. Please try again.",
        "msg_phone_verified" : "Phone number verified.",
        "msg_phone_verification_timeout" : "Input timeout. Please try again.",
        "msg_code_empty" : "Please fill out the verification code.",
        "msg_phone_not_verified" : "Phone number must be verified.",
        // 전화번호인증 end        
        "msg_is_sync_data" : "Is the length of the video the same as the flight record?",
        "msg_youtube_uploaded" : "Click the \"Apply\" button to modify the content.",
        "msg_do_login" : "This service requires Sign-In.",
        "msg_login_another_device_sorry": "You have logged in from another device or there is a temporary problem, sorry.",
        "msg_notice": "* The total flight time is calculated from flight records uploaded after September 9, 2020.",
        "msg_no_mission": "There is no mission or something wrong.",
        "msg_stop_share_before_remove": "This is a shared record. Please turn off sharing first.",
        "msg_error_sorry": "Error. Sorry, please try again later.",
        "msg_error": "Error.",
        "msg_show_token":"Show token",
        "msg_hide_token":"Hide token",
        "msg_error_same_record_exist": "The same flight record exists. Please delete the previous flight record and upload it again or upload another flight record.",
        "msg_failed_to_load_map_sorry": "Failed to load map, sorry. Please, try again later.",
        "msg_sorry_now_on_preparing": "Sorry. Currently, this feature is in preparation.",
        "msg_sorry_now_on_preparing_youtube": "Sorry. Currently, this feature is in preparation. After uploading the video from the YouTube site, you can set the link of the created video in 'YouTube Video URL'.",
        "msg_no_data": "There is no data",
        "msg_no_email": "The E-mail address is not exist.",
        "msg_modify": "Modify",
        "msg_remove": "Delete",
        "msg_apply": "Apply",
        "msg_cancel": "Cancel",
        "msg_agree": "I Agree",
        "msg_register": "Register",
        "msg_back": "Back",
        "msg_upload": "Upload",
        "msg_no_flight_record": "There is no flight record or something wrong.",
        "msg_failed_to_get_position": "Failed to get object position",
        "msg_load_more": "More ...",
        "msg_you_are_not_member": "You are not registered here.",
        "msg_are_you_sure": "Are you sure ?",
        "msg_modify_memo": "Update Memo",
        "msg_modify_tag": "Update Tag",
        "msg_fill_memo": "Memo is empty. Please, write something.",
        "msg_fill_tag": "Tag is empty. Please, write something.",
        "msg_success": "Success",
        "msg_tracker": "Move map to the current location",
        "msg_register_success": "Congratulation!! Successfully, registered !",
        "msg_email_is_already_exist": "Email is already in use. Please, enter another email.",
        "msg_name_is_already_exist": "Already in use. Please, enter another name.",
        "msg_input_name": "Please, enter your name.",
        "msg_input_email": "Please, enter your email.",
        "msg_input_member_email": "Please enter DUNI PILOT Center member's email address.",
        "msg_sure_for_public": "Are you sure to share this flight record ?",
        "msg_input_phone": "Please, enter your phone-number.",
        "msg_input_mission_name": "Please, Input Mission name.",
        "msg_input_record_name": "Please, Input flight record name.",
        "msg_wrong_input": "Please input valid data.",
        "msg_wrong_youtube_url_input": "Invalid Youtube url.",
        "msg_input_speed": "Please enter the speed when performing the flight mission.  (m/s)",
        "msg_error_index_pre": "Error : Index - ",
        "msg_error_index_post": " / There is empty parameter.",
        "msg_error_check": "Please, check errors.",
        "msg_select_file": "Please, select flight-record file.",
        "msg_select_another_file": "Can't analyze the flight record file. Please select a different file.",
        "msg_select_video_file" : "Please, select video file.",
        "msg_select_any_file": "Please, select any flight-record file or enter a Youtube URL",
        "msg_modify_youtube_data": "Modify youtube info",
        "msg_close_youtube_data": "Close youtube info",
        "msg_dji_file_upload": "DJI Flight-record file",
        "msg_duni_file_upload": "DUNI Flight-record file",
        "msg_record_search_key": "Flight record search",
        "msg_mission_search_key": "Flight mission search",
        "msg_address_checked": "Checked !",
        "msg_video_upload_success": "Successfully uploaded !!",
        "msg_input_corrent_address" : "Please enter a valid address and click 'Check address'.", 
        "tab_menu_upload_selector_address" : "Enter the address of the location",
        "badgeHelpContent": "Please copy and paste the code below into the home page, blog, or website posts where you can insert the 'html' code. You can prove your flight records naturally and beautifully.",
        "more_label": "More ...",
        "open_record_label": "Flight records",
        "label_set_youtube_url": "Enter Youtube URL",
        "label_set_no_video": "No video",
        "label_upload_movie": "Upload video file",
        "tab_menu_upload_selector_dji": "Upload flight-record",
        "tab_menu_upload_selector_address": "Detailed address",
        "latitude_label": "Latitude",
        "longitude_label": "Longitude",
        "altitude_label": "Altitude",
        "roll_label": "roll",
        "pitch_label": "pitch",
        "yaw_label": "head",
        "speed_label": "speed(m/s)",
        "action_label": "Action",
        "help_label": "Help",
        "Aerial_label": "Aerial",
        "Aerial_label_label": "Aerial with labels",
        "Road_label": "Road",
        "average_alltime_label": "Average flight time for all members(min.)",
        "average_rcount_label": "Average number of flights for all members",
        "r_count_label": "Number of flights",
        "f_count_label": "Number of flight missions",
        "a_time_label": "Total flight time",
        "a_time_min_label": "minute(s)",
        "callsign_pre_label": "DUNI PILOT",
        "dji_flight_record_get_label": "How to get the file : Click",
        "duni_flight_record_format_label": "DUNI Flight record format (Click)",
        "page_center_title": "DUNI PILOT Center",
        "page_list_title": "Flight Mission List",
        "page_flight_rec_view_title": "My Flight Record View",
        "page_flight_rec_public_view_title": "Public Flight Record View",
        "page_flight_rec_upload_title": "Flight Record Upload",
        "page_monitor_title": "Drone location",
        "page_mission_design_title": "Flight Mission Design",
        "page_dromi_title": "Dromi",
        "page_dromi_list_title": "Dromi Data View",
        "mission_about_content": "Search the flight plan you designed.",
        "fill_info_label": "Please fill the form in and click the 'Register' button.",
        "register_explain_label": "If you agree with the 'Privacy Policy' below, please click the 'I agree' button below.",
        "record_list_about_content": "Review your flight !",
        "record_public_list_about_content": "You can see flight records of other members.",
        "monitor_about_content": "Check your drone's location in realtime.",
        "upload_about_content": "Upload your flight record.",
        "design_about_content": "You can easily design the drone's flight mission",
        "head_pilot_title": "Pilot Center for Pilot",
        "head_developer_title": "Pilot Center for Lab",
        "center_about_pilot_title": "About Pilot View",
        "center_about_developer_title": "About Lab",
        "center_about_pilot_content": "This is where you can easily design the drone's flight mission and check flight records and the situation." +
            "The flight mission you designed can be used in DUNI app and in the drone of DJI product. DUNI app is currently under development and Android/iOS version will be distributed soon.<br>" +
            "Upload the Drone's video to Youtube site or set Youtube URL with the video to see detailed flight records. ('Flight record' > 'Upload record' Menu)",
        "center_about_developer_content": "This is where you can easily design the drone's flight mission and check flight records and the situation." +
            "The flight mission you designed can be used in DUNI app and in the drone of DJI product. DUNI app is currently under development and Android/iOS version will be distributed soon.<br>" +
            "The Android version of the DUNI app has a source code and it is opened. <a href='http://code.duni.io/' target=_new>Here</a><br>" +
            "Upload the Drone's video to Youtube site or set Youtube URL with the video to see detailed flight records. ('Flight record' > 'Upload record' Menu)<br>" +
            "Click <i class='fa fa-user fa-fw'></i> icon at the top to see your developer Token.",
        "dev_token_title": "Token for Developer",
        "collapseRecordFileParams": "<br><hr size=1><p><b>Android</b></p>"
            + "<p>- My file > Internal storage > DJI > dji.go.v4 > FlightRecord > FlightRecord_yyyymmddhh.txt</p>"
            + "<p>Or, - My file > Internal storage > DJI > com.dji.industry.pilot > FlightRecord > FlightRecord_yyyymmddhh.txt</p>"
            + "<p>Or, - My file > Internal storage > DJI > [APP NAME] > FlightRecord > FlightRecord_yyyymmddhh.txt</p>"
            + "<br><p><b>iOS (Please, refer to links below)</b></p>"
            + "<p>- <a href='https://m.blog.naver.com/PostView.nhn?blogId=apache81&logNo=220423814490' target=new>https://m.blog.naver.com/PostView.nhn?blogId=apache81&logNo=220423814490</a></p>"
            + "<p>- <a href='http://blog.daum.net/dipod/857' target=new>http://blog.daum.net/dipod/857</a></p>"
            + "<p>- <a href='https://www.youtube.com/watch?v=59pE9N3pXdg' target=new>https://www.youtube.com/watch?v=59pE9N3pXdg</a></p>",
            
         "youtubeTOS" : "By submitting a video to YouTube, you agree to the YouTube <a href='https://www.youtube.com/t/terms' target=_new>Terms of Service</a> and <a href='https://www.youtube.com/yt/about/policies/' target=_new>Community Guidelines</a>.",
    }
};
